// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import PushController from "./push_controller"
application.register("push", PushController)